### ISSUE TITLE
Are DirectX 9 and 10 actually supported?

### ISSUE THREAD

**Issue by Serentty** [DragonJoker/Ashes#282]
The [Vulkan website](https://www.vulkan.org/porting) has a page where it lists Ashes as a project that can layer Vulkan on top of DirectX 9, 10, and 11. However, looking at both the readme and the code tree here, I do not see any mention of those earlier DirectX versions. Is this a mistake a Vulkan website that warrants correcting, or is this an issue with the documentation for Ashes?

![image](https://github.com/DragonJoker/Ashes/assets/614548/03d1c695-596e-42b5-8934-e28a1dee30d8)

**Comment by DragonJoker** [comment]
Hi !
Ashes only supports DirectX11, so yes, it's a mistake from Vulkan's website
